name: Greetings

on: 
 push:
   branches: [ main ]
     

jobs:
  greeting:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: touch /tmp/serge
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
